spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: neils110@gmail.com
    password: th942578
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true